### ISSUE TITLE
compute_areas_2 undefined without numba

### ISSUE THREAD

**Issue by schluenz** [praxes/hexrd#101]
Hi, 

without numba being installed, hexrd complains about: 

  File "/usr/lib64/python2.7/site-packages/hexrd/xrd/xrdutil.py", line 3652, in <module>
    npdiv=1, quiet=False, compute_areas_func=compute_areas_2):
NameError: name 'compute_areas_2' is not defined

As far as I can see compute_areas_2 is only declared within an "if USE_NUMBA" block. 

Cheers, Frank.

**Comment by joelvbernier** [comment]
I will change the defaults to use the non-Numba "compute_areas"

**Comment by joelvbernier** [comment]
Fixed in praxes/master.

On Nov 25, 2015, at 03:50 AM, schluenz <notifications@github.com> wrote:

Hi,
without numba being installed, hexrd complains about:
File "/usr/lib64/python2.7/site-packages/hexrd/xrd/xrdutil.py", line 3652, in 
npdiv=1, quiet=False, compute_areas_func=compute_areas_2):
NameError: name 'compute_areas_2' is not defined
As far as I can see compute_areas_2 is only declared within an "if USE_NUMBA" block.
Cheers, Frank.

**Comment by joelvbernier** [comment]
Fixed now, with reference to the compute_areas functions in gridutil, which has a non-numbs fallback.
